### ISSUE TITLE
AIO Fighter not functioning

### ISSUE THREAD

**Issue by wsock** [chsami/Microbot#264]
### **Bug description**
Currently **doesn't** draw radius of attack, or even attack an enemy listed within the "`Attackable NPCs`" section. Automatically switches attack styles even when not having the boxes checked. Will randomly go into defensive mode or other styles when the box `Balance Combat Skills` is off.

### **Side Notes**
Loading an older version of microbot before these changes were pushed allows for AIO Fighter to return back to its original functionality. (Rendering Attack Radius, and highlighting enemies which match the name within the Attackable NPCs)

**Comment by See1Duck** [comment]
The bug is caused by old saved settings conflicting with the new ones, this issue should be resolved by pressing the reset button at the bottom, also make sure to read the new instructions, you now set the center tile by Shit + Right click. 

If you don't want it to change attack styles make sure to set the target level lower or equal to your current level in that particular skill. 

Hope this helps!

**Comment by chsami** [comment]
@wsock Issue fixed?
